/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlihocsinh.UI.nhanvien;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import quanlihocsinh.UI.Main;

/**
 *
 * @author DELL
 */
public class XepGVCN extends javax.swing.JPanel {

    /**
     * Creates new form XepGVCN
     */
    private JComboBox<String> teachersComboBox;
    private GVCNTableModel tableModel;
    
    public XepGVCN() {
        initComponents();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Giáo Viên Chủ Nhiệm");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Lớp", "Giáo viên"
            }
        ));
        jScrollPane1.setViewportView(table);

        saveButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        saveButton.setText("Lưu");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cancelButton.setText("Hủy");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        loadTableData();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(!checkGVCN()) // kiem tra xem co giao vien nao chu nhiem 2 lop tro len khong
            return;
        try {
            Connection connection = Main.sqlConnection.getConnection();
            Statement statement = connection.createStatement();
            for(int i = 0; i < table.getRowCount(); i++) {
                String className = table.getValueAt(i, 1).toString();
                String teacher = table.getValueAt(i, 2).toString();
                String teacherID = "";
                if(teacher.equals("<Chọn>"))
                    teacherID = "NULL";
                else
                    teacherID = "'" + teacher.split(" - ")[0] + "'";
                
                statement.executeUpdate(
                        "UPDATE LOPHOC SET MaGVCN=" + teacherID + 
                        " WHERE TenLop='" + className + "'"
                );
            }
            
            connection.close();
            JOptionPane.showMessageDialog(this, "Đã cập nhật thành công!");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(XepGVCN.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadTableData() {
        try {
            Connection connection = Main.sqlConnection.getConnection();
            Statement statement = connection.createStatement();
            
            // lay danh sach lop va giao vien chu nhiem
            ResultSet rs = statement.executeQuery(
                    "SELECT TenLop, MaGVCN, TenNhanVien " +
                    "FROM LOPHOC LH LEFT JOIN NHANVIEN NV ON LH.MaGVCN=NV.MaNhanVien " +
                    "ORDER BY TenLop"
            );
            
            tableModel = new GVCNTableModel();
            int i = 0;
            while(rs.next()) {
                i++;
                String className = rs.getString(1);
                String teacherId = rs.getString(2);
                String teacherName = rs.getString(3);
                
                Vector<String> rowData = new Vector<>();
                rowData.addElement(Integer.toString(i));
                rowData.addElement(className);
                if(teacherId == null || teacherId.equals(""))
                    rowData.addElement("<Chọn>");
                else
                    rowData.addElement(teacherId + " - " + teacherName);
                
                tableModel.addRow(rowData);
            }
            
            rs.close();
            
            table.setModel(tableModel);
            // su dung combobox de chon giao vien
            loadTeacherList(statement);
            TableColumn teacherColumn = table.getColumnModel().getColumn(2);
            teacherColumn.setCellEditor(new DefaultCellEditor(teachersComboBox));
            
            connection.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(XepGVCN.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
        }
    }
    
    private void loadTeacherList(Statement statement)throws SQLException {
        teachersComboBox = new JComboBox<>();
        teachersComboBox.addItem("<Chọn>");
        ResultSet rs = statement.executeQuery("SELECT MaNhanVien, TenNhanVien FROM NHANVIEN");
        while(rs.next())
            teachersComboBox.addItem(rs.getString(1) + " - " + rs.getString(2));
        rs.close();
    }
    
    private boolean checkGVCN() {
        for(int i = 0; i < table.getRowCount() - 1; i++) {
            String s1 = table.getValueAt(i, 2).toString();
            if(s1.equals("<Chọn>"))
                continue;
            for(int j = i + 1; j < table.getRowCount(); j++) {
                String s2 = table.getValueAt(j, 2).toString();
                if(s1.equals(s2)) {
                    JOptionPane.showMessageDialog(this, "Mỗi giáo viên chỉ được chủ nhiệm 1 lớp!");
                    return false;
                }
            }
        }
        return true;
    }
    
    private class GVCNTableModel extends DefaultTableModel {
        private final String[] headers;
        
        public GVCNTableModel() {
            headers = new String[] {"STT", "Lớp", "Giáo viên"};
            setRowCount(0);
        }
        
        @Override
        public boolean isCellEditable(int row, int col) {
            return col == 2;
        }
        
        @Override
        public int getColumnCount() {
            return headers.length;
        }
        
        @Override
        public String getColumnName(int col) {
            if(col < getColumnCount())
                return headers[col];
            return "";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
