/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlihocsinh.UI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class BaoCaoTongKetHocKi extends javax.swing.JPanel {

    /**
     * Creates new form BaoCaoTongKetHocKi
     */
    public BaoCaoTongKetHocKi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        semesterComboBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Báo Cáo Tổng Kết Học Kì");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Học Kì:");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Lớp", "Sĩ Số", "Số Lượng Đạt", "Tỉ Lệ"
            }
        ));
        jScrollPane1.setViewportView(table);

        semesterComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        semesterComboBox.setForeground(new java.awt.Color(0, 0, 255));
        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        submitButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        submitButton.setText("Xem");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(submitButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            Connection connection = Main.sqlConnection.getConnection();
            Statement statement = connection.createStatement();
            
            int semester = semesterComboBox.getSelectedIndex() + 1;
            // lay muc diem dat
            ResultSet rs = statement.executeQuery("SELECT MucDiemDat FROM THAMSO");
            rs.first();
            float pointLimit = rs.getFloat(1);
            
            String sql = "SELECT TenLop, SiSo, " +
                    "COUNT(CASE WHEN DTBHocKi" + semester + ">=" + pointLimit + " THEN 1 ELSE NULL END) " +
                    "FROM LOPHOC LH LEFT JOIN HOCSINH HS ON LH.MaLop=HS.MaLop " +
                    "GROUP BY TenLop";
            System.out.println(sql);
            rs = statement.executeQuery(sql);
            showOnTable(rs);
            
            rs.close();
            connection.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(BaoCaoTongKetHocKi.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void showOnTable(ResultSet rs) throws SQLException {
        DefaultTableModel tableModel = new DefaultTableModel(
                new String[] {"STT", "Lớp", "Sĩ số", "Số lượng đạt", "Tỉ lệ"},
                5
        ) {
            @Override
            public boolean isCellEditable(int row, int col) {
                // khong cho pheep sua cac gia tri tren bang
                return false;
            }
        };
        tableModel.setRowCount(0);
        int i = 0;
        while(rs.next()) {
            Vector<String> rowData = new Vector<>();
            i++;
            String className = rs.getString(1); // ten lop
            String numOfStudentInClass = rs.getString(2); // si so
            String numOfStudentCompleted = rs.getString(3); // so luong dat
            float percentage;
            if(Integer.parseInt(numOfStudentInClass) == 0)
                percentage = (float)0;
            else {
                percentage = 100 * Integer.parseInt(numOfStudentCompleted) /
                    (float)Integer.parseInt(numOfStudentInClass);
                percentage = Math.round(percentage * 100) / (float)100; // lam tron 2 chu so
            }
            
            rowData.addElement(Integer.toString(i));
            rowData.addElement(className);
            rowData.addElement(numOfStudentInClass);
            rowData.addElement(numOfStudentCompleted);
            rowData.addElement(percentage + "%");
            
            tableModel.addRow(rowData);
        }
        table.setModel(tableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
