/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlihocsinh.UI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class BaoCaoTongKetMon extends javax.swing.JPanel {

    /**
     * Creates new form BaoCaoTongKetMon
     */
    private DefaultTableModel tableModel;
    
    public BaoCaoTongKetMon() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        subjectComboBox = new javax.swing.JComboBox<>();
        semesterComboBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Báo Cáo Tổng Kết Môn");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Môn:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Học Kì:");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Lớp", "Sĩ Số", "Số Lượng Đạt", "Tỉ Lệ"
            }
        ));
        jScrollPane1.setViewportView(table);

        subjectComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        subjectComboBox.setForeground(new java.awt.Color(0, 0, 255));

        semesterComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        semesterComboBox.setForeground(new java.awt.Color(0, 0, 255));
        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        submitButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        submitButton.setText("Xem");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(semesterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 226, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String subjectName = subjectComboBox.getSelectedItem().toString();
        int semester = semesterComboBox.getSelectedIndex() + 1;
        try {
            Connection connection = Main.sqlConnection.getConnection();
            Statement statement = connection.createStatement();
            
            // lay ma mon hoc
            ResultSet rs = statement.executeQuery(
                    "SELECT MaMonHoc FROM MONHOC WHERE TenMonHoc='" + subjectName + "'");
            rs.first();
            String subjectID = rs.getString(1);
            
            // lay muc diem dat
            rs = statement.executeQuery("SELECT MucDiemDat FROM THAMSO");
            rs.first();
            float pointLimit = rs.getFloat(1);
            
            String sql = "SELECT TenLop, SiSo," +
                    " COUNT(CASE WHEN DiemTrungBinhMon>=" + pointLimit + " THEN 1 ELSE NULL END)" +
                    " FROM LOPHOC LH LEFT JOIN (" +
                        "SELECT  MaLop, DiemTrungBinhMon " +
                        "FROM BANGDIEMMON BDM JOIN HOCSINH HS ON BDM.MaHocSinh=HS.MaHocSinh " +
                        "WHERE HocKi=" + semester + " AND MaMonHoc='" + subjectID + "')AS TB" +
                    " ON LH.MaLop=TB.MaLop" +
                    " GROUP BY TenLop";
            rs = statement.executeQuery(sql);
            tableModel = new DefaultTableModel(
                    new String[] {"STT", "Lớp", "Sĩ số", "Số lượng đạt", "Tỉ lệ"}, 5
            ) {
                @Override
                public boolean isCellEditable(int row, int col) {
                    return false;
                }
            };
            tableModel.setRowCount(0);
            while(rs.next()) {
                Vector<String> rowData = new Vector<>();
                // tinh cac gia tri
                int i = rs.getRow();
                String className = rs.getString(1);
                String numOfStudent = rs.getString(2);
                String numOfStudentCompleted = rs.getString(3);
                float percentage = 100 * Integer.parseInt(numOfStudentCompleted)
                        / (float)Integer.parseInt(numOfStudent);
                percentage = Math.round(percentage * 100) / (float)100; // lam tron den 2 chu so
                // luu vao vector
                rowData.add(Integer.toString(i));
                rowData.addElement(className);
                rowData.addElement(numOfStudent);
                rowData.addElement(numOfStudentCompleted);
                rowData.addElement(percentage + "%");
                // them vao bang
                tableModel.addRow(rowData);
            }
            table.setModel(tableModel);
            rs.close();
            connection.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(BaoCaoTongKetMon.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void initData() {
        try {
            Connection connection = Main.sqlConnection.getConnection();
            // lay danh sach mon hoc
            ResultSet rs = connection.createStatement().executeQuery(
                    "SELECT TenMonHoc FROM MONHOC");
            while(rs.next())
                subjectComboBox.addItem(rs.getString(1));
            
            connection.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(BaoCaoTongKetMon.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JComboBox<String> subjectComboBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
