/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlihocsinh.UI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class CaiDat extends javax.swing.JPanel {

    /**
     * Creates new form CaiDat
     */
    public CaiDat() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minAgeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        maxNumOfStudentInClassField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pointLimitField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        maxAgeField = new javax.swing.JTextField();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {4};
        setLayout(layout);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Thay đổi quy định");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tuổi học sinh:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 7);
        add(jLabel2, gridBagConstraints);

        minAgeField.setColumns(9);
        minAgeField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(minAgeField, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Sĩ số tối đa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        add(jLabel4, gridBagConstraints);

        maxNumOfStudentInClassField.setColumns(19);
        maxNumOfStudentInClassField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        add(maxNumOfStudentInClassField, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Mức điểm đạt:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(jLabel5, gridBagConstraints);

        pointLimitField.setColumns(19);
        pointLimitField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        add(pointLimitField, gridBagConstraints);

        saveButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        saveButton.setText("Lưu");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(saveButton, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(jLabel6, gridBagConstraints);

        maxAgeField.setColumns(9);
        maxAgeField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(maxAgeField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(!checkForm()) // kiem tra cac thong tin da duoc dien day du chua
            return;
        int minAge = Integer.parseInt(minAgeField.getText());
        int maxAge = Integer.parseInt(maxAgeField.getText());
        int maxNumOfStudentInClass = Integer.parseInt(
                maxNumOfStudentInClassField.getText());
        float pointLimit = Float.parseFloat(pointLimitField.getText());
        
        try {
            Connection connection = Main.sqlConnection.getConnection();
            connection.createStatement().executeUpdate(
                    "UPDATE THAMSO SET TuoiHocSinhToiThieu=" + minAge + ", " +
                    "TuoiHocSinhToiDa=" + maxAge + ", " + 
                    "SiSoToiDa=" + maxNumOfStudentInClass + ", " +
                    "MucDiemDat=" + pointLimit
            );
            
            connection.close();
            JOptionPane.showMessageDialog(this, "Lưu quy định thành công!");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra, hãy thử lại!");
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void initData() {
        try {
            Connection connection = Main.sqlConnection.getConnection();
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM THAMSO");
            rs.first();
            
            minAgeField.setText(rs.getString(1));
            maxAgeField.setText(rs.getString(2));
            maxNumOfStudentInClassField.setText(rs.getString(3));
            pointLimitField.setText(rs.getString(4));
            
            rs.close();
            connection.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
        }
    }
    
    // kiem tra cac gia tri da duoc dien het chua
    private boolean checkForm() {
        if(minAgeField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền tuổi tối thiểu!");
            return false;
        }
        
        if(maxAgeField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền tuổi tối đa!");
            return false;
        }
        
        if(maxNumOfStudentInClassField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền sĩ số tối đa!");
            return false;
        }
        
        if(pointLimitField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền mức điểm đạt!");
            return false;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField maxAgeField;
    private javax.swing.JTextField maxNumOfStudentInClassField;
    private javax.swing.JTextField minAgeField;
    private javax.swing.JTextField pointLimitField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
