/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlihocsinh.UI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class CaiDat extends javax.swing.JPanel {

    /**
     * Creates new form CaiDat
     */
    public CaiDat() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minAgeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        maxNumOfStudentInClassField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pointLimitField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        maxAgeField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Thay đổi quy định");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tuổi học sinh:");

        minAgeField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Sĩ số tối đa:");

        maxNumOfStudentInClassField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Mức điểm đạt:");

        pointLimitField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        saveButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        saveButton.setText("Lưu");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("-");

        maxAgeField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(maxNumOfStudentInClassField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pointLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(minAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)))
                        .addGap(10, 10, 10)
                        .addComponent(maxAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(minAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addComponent(maxAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(maxNumOfStudentInClassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(pointLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(saveButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(!checkForm()) // kiem tra cac thong tin da duoc dien day du chua
            return;
        int minAge = Integer.parseInt(minAgeField.getText());
        int maxAge = Integer.parseInt(maxAgeField.getText());
        int maxNumOfStudentInClass = Integer.parseInt(
                maxNumOfStudentInClassField.getText());
        float pointLimit = Float.parseFloat(pointLimitField.getText());
        
        try {
            Connection connection = Main.sqlConnection.getConnection();
            connection.createStatement().executeUpdate(
                    "UPDATE THAMSO SET TuoiHocSinhToiThieu=" + minAge + ", " +
                    "TuoiHocSinhToiDa=" + maxAge + ", " + 
                    "SiSoToiDa=" + maxNumOfStudentInClass + ", " +
                    "MucDiemDat=" + pointLimit
            );
            
            connection.close();
            JOptionPane.showMessageDialog(this, "Lưu quy định thành công!");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra, hãy thử lại!");
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void initData() {
        try {
            Connection connection = Main.sqlConnection.getConnection();
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM THAMSO");
            rs.first();
            
            minAgeField.setText(rs.getString(1));
            maxAgeField.setText(rs.getString(2));
            maxNumOfStudentInClassField.setText(rs.getString(3));
            pointLimitField.setText(rs.getString(4));
            
            rs.close();
            connection.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CaiDat.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
        }
    }
    
    // kiem tra cac gia tri da duoc dien het chua
    private boolean checkForm() {
        if(minAgeField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền tuổi tối thiểu!");
            return false;
        }
        
        if(maxAgeField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền tuổi tối đa!");
            return false;
        }
        
        if(maxNumOfStudentInClassField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền sĩ số tối đa!");
            return false;
        }
        
        if(pointLimitField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền mức điểm đạt!");
            return false;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField maxAgeField;
    private javax.swing.JTextField maxNumOfStudentInClassField;
    private javax.swing.JTextField minAgeField;
    private javax.swing.JTextField pointLimitField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
