/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlihocsinh.UI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import quanlihocsinh.Obj.CheckDate;
import quanlihocsinh.Obj.Student;

/**
 *
 * @author DELL
 */
public class TraCuuChiTiet extends javax.swing.JPanel {

    /**
     * Creates new form TraCuChiTiet
     */
    private Student student;
    
    public TraCuuChiTiet() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        gradeField = new javax.swing.JTextField();
        classField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        sexField = new javax.swing.JComboBox<>();
        d_birthdayComboBox = new javax.swing.JComboBox<>();
        m_birthdayComboBox = new javax.swing.JComboBox<>();
        y_birthdayField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        avgT1Field = new javax.swing.JTextField();
        avgT2Field = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {30};
        setLayout(layout);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Chi tiết học sinh:");
        add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Họ Tên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Khối:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Lớp:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Giới Tính:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 0);
        add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Ngày sinh:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 0);
        add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Địa Chỉ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 0);
        add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        add(jLabel8, gridBagConstraints);

        nameField.setColumns(15);
        nameField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nameField.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(nameField, gridBagConstraints);

        gradeField.setEditable(false);
        gradeField.setColumns(15);
        gradeField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gradeField.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 1);
        add(gradeField, gridBagConstraints);

        classField.setEditable(false);
        classField.setColumns(15);
        classField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        classField.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(classField, gridBagConstraints);

        addressField.setColumns(15);
        addressField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addressField.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 0);
        add(addressField, gridBagConstraints);

        sexField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sexField.setForeground(new java.awt.Color(0, 0, 255));
        sexField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(sexField, gridBagConstraints);

        d_birthdayComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        d_birthdayComboBox.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(d_birthdayComboBox, gridBagConstraints);

        m_birthdayComboBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        m_birthdayComboBox.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(m_birthdayComboBox, gridBagConstraints);

        y_birthdayField.setColumns(5);
        y_birthdayField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        y_birthdayField.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(y_birthdayField, gridBagConstraints);

        emailField.setColumns(15);
        emailField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        add(emailField, gridBagConstraints);

        jLabel9.setText("TB HK 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        add(jLabel9, gridBagConstraints);

        jLabel10.setText("TB HK 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        add(jLabel10, gridBagConstraints);

        avgT1Field.setEditable(false);
        avgT1Field.setColumns(5);
        avgT1Field.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        avgT1Field.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(avgT1Field, gridBagConstraints);

        avgT2Field.setEditable(false);
        avgT2Field.setColumns(5);
        avgT2Field.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        avgT2Field.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        add(avgT2Field, gridBagConstraints);

        saveButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        saveButton.setText("Lưu");
        saveButton.setToolTipText("Lưu thông tin học sinh đã thay đổi");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 4;
        add(saveButton, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Mã Học Sinh:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel11, gridBagConstraints);

        idField.setEditable(false);
        idField.setColumns(15);
        idField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        idField.setForeground(new java.awt.Color(0, 0, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        add(idField, gridBagConstraints);

        deleteButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deleteButton.setText("Xóa");
        deleteButton.setToolTipText("Xóa học sinh ra khỏi hệ thống");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        add(deleteButton, gridBagConstraints);

        cancelButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cancelButton.setText("Hủy");
        cancelButton.setToolTipText("Hủy các thông tin vừa nhập");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        add(cancelButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String studentId = student.getID();
        int reply = JOptionPane.showConfirmDialog(
                this,
                "Bạn có muốn xóa học sinh " + studentId + " ra khỏi hệ thống?",
                "Xóa học sinh",
                JOptionPane.YES_NO_OPTION
        );
        if(reply == JOptionPane.YES_OPTION) {
            try {
                Connection connection = Main.sqlConnection.getConnection();
                Statement statement = connection.createStatement();
                
                // Xoa bang diem hoc sinh
                statement.executeUpdate("DELETE FROM BANGDIEMMON WHERE MaHocSinh='" + studentId + "'");
                // Xoa hoc sinh
                statement.executeUpdate("DELETE FROM HOCSINH WHERE MaHocSinh='" + studentId + "'");
                connection.close();
                
                TraCuuHocSinh.deleteSelectedStudent();
                JOptionPane.showMessageDialog(this, "Đã xóa thành công học sinh " + studentId);
                setVisible(false);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(TraCuuChiTiet.class.getName()).log(Level.SEVERE, null, ex);
                Main.sqlConnection.closeAllConnection();
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        loadStudentInfo();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(!checkEmptyField()) // kiem tra xem thong tin da duoc dien day du chua
            return;
        
        int d = d_birthdayComboBox.getSelectedIndex() + 1;
        int m = m_birthdayComboBox.getSelectedIndex() + 1;
        int y = Integer.parseInt(y_birthdayField.getText());
        if(!CheckDate.checkValidDate(d, m, y)) {
            JOptionPane.showMessageDialog(this, "Ngày tháng không hợp lệ!");
            return;
        }
        
        try {
            Connection connection = Main.sqlConnection.getConnection();
            Statement statement = connection.createStatement();
            
            // kiem tra gioi han ve tuoi
            String[] checkBirthDayLim = CheckDate.checkBirthdayLimit(y, statement).split(",");
            if(checkBirthDayLim[2].equals("false")) {
                JOptionPane.showMessageDialog(
                        this,
                        "Tuổi học sinh phải từ " + checkBirthDayLim[0] + " đến " + checkBirthDayLim[1]
                );
                connection.close();
                return;
            }
            
            // lay cac thong tin hoc sinh
            String id = idField.getText();
            String name = nameField.getText();
            int sex = sexField.getSelectedIndex();
            String address = addressField.getText();
            String email = emailField.getText();
            
            // tao chuoi ngay sinh
            Date date = new GregorianCalendar(y, m - 1, d).getTime();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String birthday = df.format(date);
            
            statement.executeUpdate("UPDATE HOCSINH SET"
                    + " HoVaTen='" + name + "', GioiTinh=" + sex + ", DiaChi='"
                    + address + "', Email='" + email + "', NgaySinh='"
                    + birthday + "' WHERE MaHocSinh='" + id + "'"
            );
            
            connection.close();
            student.setName(name);
            student.setSex(sex);
            student.setAddress(address);
            student.setEmail(email);
            student.setBirthday(birthday);
            TraCuuHocSinh.reloadTable();
            JOptionPane.showMessageDialog(this, "Lưu thông tin thành công!");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(TraCuuChiTiet.class.getName()).log(Level.SEVERE, null, ex);
            Main.sqlConnection.closeAllConnection();
        }
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void initData() {
        // hien thi danh sach ngay, thang
        for(int i = 0; i < 31; i++)
            d_birthdayComboBox.addItem(Integer.toString(i + 1));
        for(int i = 0; i < 12; i++)
            m_birthdayComboBox.addItem(Integer.toString(i + 1));
    }
    
    public void setStudent(Student student) {
        this.student = student;
        loadStudentInfo();
    }
    
    private void loadStudentInfo() {
        idField.setText(student.getID());
        nameField.setText(student.getName());
        gradeField.setText(Integer.toString(student.getGrade()));
        classField.setText(student.getClassName());
        sexField.setSelectedIndex(student.getSex());
        
        String[] birthday = student.getBirthday().split("-"); // dinh dang yyyy-MM-dd
        d_birthdayComboBox.setSelectedIndex(
                Integer.parseInt(birthday[2]) - 1);
        m_birthdayComboBox.setSelectedIndex(
                Integer.parseInt(birthday[1]) - 1);
        y_birthdayField.setText(birthday[0]);
        
        addressField.setText(student.getAddress());
        emailField.setText(student.getEmail());
        avgT1Field.setText(Float.toString(student.getAVGT1()));
        avgT2Field.setText(Float.toString(student.getAVGT2()));
    }
    
    // kiem tra xem cac thong tin da duoc dien day du chua
    
    private boolean checkEmptyField() {
        if(nameField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tên không được để trống!");
            return false;
        }
        
        if(y_birthdayField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tên không được để trống!");
            return false;
        }
        
        if(addressField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống!");
            return false;
        }
        
        if(emailField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Email không được để trống!");
            return false;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField avgT1Field;
    private javax.swing.JTextField avgT2Field;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField classField;
    private javax.swing.JComboBox<String> d_birthdayComboBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField gradeField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> m_birthdayComboBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> sexField;
    private javax.swing.JTextField y_birthdayField;
    // End of variables declaration//GEN-END:variables
}
